function dz = construct_data(z,coe,coupling_mat) 
% Evaluate the function
    if length(coe) == 10
        dz = coe(1) + coe(2).*z + coe(3).*conj(z) + coe(4).*(z.*z)...
            + coe(5).*(z.*conj(z)) + coe(6).*(conj(z.*z)) + coe(7).*(z.*z.*z)...
            + coe(8).*(z.*z.*conj(z)) + coe(9).*(z.*(conj(z.*z))) +coe(10).*(conj(z.*z.*z))...
            + coupling_mat*z;
    elseif length(coe) == 4
        dz = coe(1) + coe(2).*z + coe(3).*(conj(z.*z)) + coe(4).*(z.*z.*z) + coupling_mat*z;
    elseif length(coe) == 11
    dz = coe(1) + coe(2).*z + coe(3).*conj(z) + coe(4).*(z.*z)...
        + coe(5).*(z.*conj(z)) + coe(6).*(conj(z.*z)) + coe(7).*(z.*z.*z)...
        + coe(8).*(z.*z.*conj(z)) + coe(9).*(z.*(conj(z.*z))) +coe(10).*(conj(z.*z.*z))...
        + coe(11)*coupling_mat*z;
    dz = dz*1i;
    elseif length(coe) == 5
     dz = coe(1) + coe(2).*z + coe(3).*(z.*z)+ coe(4).*(z.*z.*z)...
        + coe(5)*coupling_mat*z;   
    end
end